### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by IshaDakota** [MarchingLizard/iwiorg#1]
These are the fonts included in the design:
Avenir
Lato
Open Sans

All but Avenir are available as Google Fonts, can we use Nunito as substitute so that we dont need to host fonts? See comparison:

http://joelcrawfordsmith.com/closest-font/font/avenir

**Comment by Shorashim** [comment]
That's okay!

**Comment by IshaDakota** [comment]
Using Nunito
