### ISSUE TITLE
Pay It Forward Webform

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#100]
Is it possible to add something for the "your name" section before you refer friends to see if they are interested/eligible in going on Birthright? I am receiving many submissions that just have one name on them, so I want to make sure we are not missing out on potential applicants who are missing the idea behind the sweepstakes

**Comment by IshaDakota** [comment]
Don't understand ^^

**Comment by Shorashim** [comment]
Many people are entering just one name under your name and no info under it. I think it would make sense to there be a field where people can make if they are referring people as an alum or as someone who also want to travel. Does that make sense?
![screen shot 2015-08-17 at 8 37 39 pm](https://cloud.githubusercontent.com/assets/13404688/9320444/d732627a-451f-11e5-8c89-7ac90ca7ac86.png)
