### ISSUE TITLE
Create Shorashim Live Section - Instagram, Blog, Facebook

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#101]
How do we have it update pictures? Right now, it is just what we put in as fillers

**Comment by IshaDakota** [comment]
It's static now. We need to build the "live" section for facebook and Instagram. My understanding was that you wanted to be able to filter Instagram posts.... that's the hard part.

**Comment by Shorashim** [comment]
I want to pull a live section just from @ShorashimIsrael so that I have control over what's posted, but it updates with the most up-to-date pictures. Is that doable?
