### ISSUE TITLE
Staffing Header

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#102]
Can we fix this so that the slicing extends through the entire image header?

![screen shot 2015-08-17 at 5 24 37 pm](https://cloud.githubusercontent.com/assets/13404688/9317976/e93b88d6-4504-11e5-8096-5dcf69ca1a8b.png)

**Comment by IshaDakota** [comment]
Yes. It is linking to the old image - Daniel sent us a new one.

**Comment by IshaDakota** [comment]
merged
