### ISSUE TITLE
Additions to FAQ

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#103]
Can we please add this? Birthright just sent us this update.

+ When and how will I get the deposit back?

- If you are accepted to a trip and cancel prior to the Birthright Israel deadline dates or are not accepted to participate in a program this round, your deposit will be refunded via your original method of payment. In order to receive this refund, you must submit a written request to your Shorashim directly. Should you not make this request your deposit will remain with us throughout the season and then will be refunded automatically at the conclusion of the season's trips.  After you successfully participate in a Birthright Israel trip, you may voluntarily donate all or part of your deposit in order to sponsor future Birthright Israel trips. If you are from the United States or Canada, approximately five days after you successfully complete your trip, you will be notified by email that your deposit is available to be refunded. That email may also contain information about how you can voluntarily donate all or part of your deposit in support of future Birthright Israel trips.  Note that your deposit will be used to benefit future Birthright Israel participants if it is not retrieved within 30 days of your return.  

* Please note: All deposits are charged in U.S. dollars and therefore are converted from your local currency to U.S. dollars on your credit card statements. Since they are converted using the daily U.S. dollar rate and are refunded using the daily rate on the day the refund is processed, variances often occur.

**Comment by IshaDakota** [comment]
Instructed lauren in this - will add new issue (lower priority) on making this more intuitive.
