### ISSUE TITLE
Change Share the Gift Menu Items

### ISSUE THREAD

**Issue by IshaDakota** [MarchingLizard/iwiorg#105]
From Issue #96 
is it possible to have it as follows:
Pay It Forward
Become an Ambassador
Campus Recruiting Program

Could we anchor to that header on each page? Just a thought!

**Comment by IshaDakota** [comment]
@Shorashim Can we hold this to the SEO review... I have a feeling their my be impact with anchors in the menu. It is possible though.

**Comment by Shorashim** [comment]
Sounds good. I added a label for SEO related issues to keep us organized with that. Hope thats okay!
