### ISSUE TITLE
Accordians for FAQ showing up on four pages

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#119]
How do we fix this? It is not showing up as one fluid page, but rather a page where you need to click through four pages to read all of them.

**Comment by IshaDakota** [comment]
This is fixed and made permanent. Can you check to see that everything is in the right place? If so, close.

**Comment by Shorashim** [comment]
I think the safety and security page looks weird. Overview should either be an accordion as well or they should all be headers like "Overview" so it is consistent. Does that make sense/do you agree?
