### ISSUE TITLE
Alumni Page

### ISSUE THREAD

**Issue by IshaDakota** [MarchingLizard/iwiorg#12]
#10 

Use this queue to start any issues.

**Comment by IshaDakota** [comment]
![alumni___site-install_and_alumni-updated_psd___100___shorashim_org__rgb_8____and_led_cinema_display](https://cloud.githubusercontent.com/assets/688507/8889757/fb6fb528-32ac-11e5-9a41-e05ed0f1f1ae.png)

**Comment by Shorashim** [comment]
Can they text be a little more spaced out? It looks a like squished. Do you agree?

**Comment by IshaDakota** [comment]
I think the line height in the text is OK (follows the golden ratio - http://alistapart.com/article/more-meaningful-typography), but I think the headers need more space.

Open an issue for that and we will deal with that globally for all pages.

**Comment by Shorashim** [comment]
Sounds good. Maybe just the spacing between sections? I think it the area between the body and header just seems tight, but I could definitely be wrong (and if I am, just let me know!)

**Comment by Shorashim** [comment]
Am I able to login and edit the text? It doesn't seem to show up on the development page, but I don't think the refer your friends part makes sense or looks good like that, so I want to just link "Nominate your friends". Thanks!

**Comment by IshaDakota** [comment]
@Shorashim no, it's not updated, and I wouldn't edit text yet - it's still to early.
