### ISSUE TITLE
Get More Information

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#129]
Can we change this to say Chat With Us and link to http://israelwithisraelis.us4.list-manage.com/subscribe?u=06a7506e1207e2586be022c5e&id=0c5a3a1869? Per the request of Birthright ASAP. Thanks!

**Comment by Shorashim** [comment]
IMPORTANT: Instead of what I had originally requested, we want to delete the "get more information" button under the video. Instead, we want to add a button under the "pre-register now" green hover button that says "Chat with Us" that links to http://eepurl.com/ymSBv. It should be blue and same design.

**Comment by IshaDakota** [comment]
I need a design for this.

**Comment by Shorashim** [comment]
https://www.dropbox.com/s/imzudumxiipjv75/chat-with-us.png?dl=0

This should work.
