### ISSUE TITLE
Tell Your Friends page missing design

### ISSUE THREAD

**Issue by IshaDakota** [MarchingLizard/iwiorg#15]
@Shorashim
There doesn;t appear to be a layer or a special design for the "Tell you Friends page" that is a submenu item of "Your Application." Do we need to have that made or is it in existence somewhere?

**Comment by Shorashim** [comment]
It should just link to the share the gift page. We just wanted the option to spread the word to be in as many places as possible. Does that work if it links to a different section?

**Comment by IshaDakota** [comment]
I see. No problem.

I guess it's a little weird for a menu item to take you off of the site.
But we do that with the current site as well, so I guess it's OK.

**Comment by Shorashim** [comment]
It would still be on the site, just within a different area of the site. Is that less weird?

**Comment by IshaDakota** [comment]
Oh. Maybe I'm not understanding. Is there a design that exist for that
page? Where does it sit in the menu?

**Comment by Shorashim** [comment]
It should just link to pay it forward or share the gift, which is where the ambassador/recruiter/pay it forward info is. Which do you think makes more sense? Pay it forward? There is a full design for both.

**Comment by IshaDakota** [comment]
I see now. OK, I'm not sure it makes sense to have it as a menu item here because it may disrupt the flow of a user browsing. But maybe not. It will be easy enough to see in testing. I'm going to close this issue, because we don't need a new design.
