### ISSUE TITLE
Address

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#157]
Can we please change the address ASAP to the following?

Address:
216 West Evergreen, Unit A1
Chicago, IL, 60642

Mailing Address:
1415 North Dayton Street, Unit A1
Chicago, IL, 60642

**Comment by IshaDakota** [comment]
where is the address on this site?

**Comment by Shorashim** [comment]
Sorry about that! I could have sworn it was in the footer.

**Comment by IshaDakota** [comment]
haha - yeah, it's not there as fas as I can see.
