### ISSUE TITLE
Accordion Text

### ISSUE THREAD

**Issue by IshaDakota** [MarchingLizard/iwiorg#17]
@shorashim
Is the text with "+" signs next to them supposed to be accordion boxes (hide/unhide):
<img width="1209" alt="important_travel_info___site-install" src="https://cloud.githubusercontent.com/assets/688507/9014458/15f9720a-3788-11e5-9d76-15f3a649890d.png">

I'm assuming so, and if that's the case, we are going to leave as plain text now and work on that feature later after we get all of the page types done. OK?

**Comment by Shorashim** [comment]
You are correct and yes-sounds perfect!
