### ISSUE TITLE
 Trip landing pages.

### ISSUE THREAD

**Issue by IshaDakota** [MarchingLizard/iwiorg#21]
@shorashim In finishing up all of the designed trip pages, we are noticing that there are no individual pages for each trip options design. Is this intentional? It seems that each trip on the trip options page should link to an individual page for that option. Or are users just supposed to view the trip options and their taxed on that single page?

**Comment by Shorashim** [comment]
I believe the intention was that it was on a single page to remain cleaner and then it would anchor to each section/option. Does that work? I can check in with Daniel if need be, but let me know if that makes sense. I believe we discussed that things are moving away from so many pages.

**Comment by IshaDakota** [comment]
That does make sense. I think it should work well.
