### ISSUE TITLE
Blog Images

### ISSUE THREAD

**Issue by IshaDakota** [MarchingLizard/iwiorg#24]
@Shorashim 

The blog uses 2 images: one for the header (top of the post) and one as the thumbnail for listing.  Do you want this to be the same image? That would be more maintainable, but would require that you choose an image that looks OK in both panorama and landscape.  I don;'t think that would be too hard.

The alternative is to have 2 separate photo fields: 1 for the header and 1 for the thumbnail.

**Comment by Shorashim** [comment]
Do you recommend that we have it be the same? I am okay doing the same if we think it is possible that enough pictures will look good for both, but if it will be better for us to have two fields, I will do two

**Comment by IshaDakota** [comment]
Let's try it with one field - I think that will be easiest in the long run. If we see in the first month or so it's too hard to get proper images we will rethink.

**Comment by Shorashim** [comment]
Sounds good
