### ISSUE TITLE
Start/Update Your Application

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#26]
Is it impossible to have it be coded like the buttons "how to register", "start/update application, etc.? 

Double checking if I am supposed to upload this in its entirety

**Comment by IshaDakota** [comment]
not sure I understand?

**Comment by Shorashim** [comment]
When you click on the buttons that are coded, it highlights, rather than just being an embedded image. From our convo earlier, it seemed like you wanted me to embed both button images here and upload the text. Is this our only option or can they be buttons like those on the top? I hope that makes sense.
