### ISSUE TITLE
Share The Gift Page

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#27]
*Very important*

There are different layers on this page. The share the gift page needs to include ambassadors, campus recruiters, and Pay It Forward. The Pay It Forward page needs to be separately linkable to shorashimpayitforward.com. Based on our conversation before, are there design changes that need to be made on this?

I am at the office now, so I have everything more accessible. If it is easier to call me, I am around, but very important that this functions properly.

**Comment by Shorashim** [comment]
![screen shot 2015-08-09 at 1 08 24 pm](https://cloud.githubusercontent.com/assets/13404688/9156219/c56b3460-3e97-11e5-8f69-4e905be6033d.png)

**Comment by Shorashim** [comment]
and separate page:
![screen shot 2015-08-09 at 1 09 17 pm](https://cloud.githubusercontent.com/assets/13404688/9156222/dc7c1714-3e97-11e5-9e9b-dab3a32e1fa0.png)

**Comment by IshaDakota** [comment]
OK, are those two separate menu items?

**Comment by Shorashim** [comment]
We can have Pay It Forward dropdown on the Share The Gift menu item if that will help. It should also link from the main Share The Gift page.

**Comment by IshaDakota** [comment]
The "Share the gift page" is the only page you have that uses right and left aligned images inline with text. Are you sure you want it this way. There will be no way to make it look great on smaller screens.

**Comment by Shorashim** [comment]
We can center align it then. When can we expect to see it by?

**Comment by IshaDakota** [comment]
^^ The answer to that question is always as soon as possible.

**Comment by Shorashim** [comment]
Thanks :)

**Comment by IshaDakota** [comment]
;) :+1:

**Comment by Shorashim** [comment]
For these, I think it makes most sense if they are almost like headers that go all the way across. The photos in full size are in the dropbox. Please let me know if you need anything else with this.

**Comment by Shorashim** [comment]
Images need to be added (3 headers) for share the gift. Pay It Forward page needs to link
