### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#28]
HOMEPAGE

*SLIDERS*
Picture yourself in Israel--->israelwithisraelis.com/departure-dates
Experience the adventure-->http://www.israelwithisraelis.com/about
Israel With Israelis-->Can we have this be editable for pre-registration/registration and link to the registration page-->bit.ly/ShorashimPreRegisterNow
See Israel through the eyes of the locals-->http://www.israelwithisraelis.com/about

*REGISTRATION BAR*
-Needs to be adapted for pre-registration
-Once adapted, pre-register now-->bit.ly/ShorashimPreRegisterNow

*Where is the Pay It Forward slider? Creating separate issue report for this, but should link to shorashimpayitforward.com*

*TRIP OPTIONS*
-Should be linked to anchors within the trip options page
---@IshaDakota Do I need to create these anchors?
-Note: Birthright plus needs to be removed from this as shown in alternative PSD example

*LOGOS*
-Need to be linked-can I do this? Please see other issue in regards to this

*Subscribe Bar*
-Needs to link to mailing list sign up

**Comment by IshaDakota** [comment]
http://www.israelwithisraelis.com/what-makes-shorashim-unique

What page is this on the new site?

**Comment by Shorashim** [comment]
Oops sorry just realized that. It would be on about us

**Comment by Shorashim** [comment]
Footer:
Do you need the individual links for footer?

*Side bar*
-Pre-register now-->bit.ly/ShorashimPreRegisterNow

*Pay It Forward*
shorashimpayitforward.com

**Comment by Shorashim** [comment]
*Social media icon links*
-Facebook: facebook.com/shorashim
-Twitter: twitter.com/shorashim
-Instagram: instagram.com/shorashimisrael
-Pinterest: pinterest.com/shorashim
-Youtube: youtube.com/user/shorashim

**Comment by Shorashim** [comment]
Shorashim logo-->israelwithisraelis.com(homepage)
Birthright logo-->birthrightisrael.com
