### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by IshaDakota** [MarchingLizard/iwiorg#3]
Create menus  and layout for header

**Comment by IshaDakota** [comment]
There are no icon files for the social media files - should they be an icon font? If so, which one?

**Comment by IshaDakota** [comment]
![home___site-install](https://cloud.githubusercontent.com/assets/688507/8764234/11054762-2d90-11e5-9eb3-2de0ca07c0e5.png)

**Comment by IshaDakota** [comment]
Todo/Qs:
- [ ] font awesome does not have snapchat icon
- [ ] what is the graph icon?
- [ ] design calls for layout wider than standard bootstrap grid - should we adjust?

**Comment by IshaDakota** [comment]
current dev version:
![home___site-install](https://cloud.githubusercontent.com/assets/688507/8765938/89f88706-2dea-11e5-8c69-c23e386f87e0.png)

**Comment by Shorashim** [comment]
Waiting to hear back from Daniel about fonts vs. images
