### ISSUE TITLE
Where do I edit the logo bar?

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#30]
It seems to be set up differently than in the past?

**Comment by IshaDakota** [comment]
Add logos under --> Add Content --> Partner Logo

**Comment by IshaDakota** [comment]
yes. It's much different - because it's a slider, each logo needs to be a piece of content

**Comment by Shorashim** [comment]
Got it! Is there a way to make sure they are all even? I see that the CJP and JUF one that are already uploaded are not even. Also, I think we need to have JUF first. I am going to upload the rest in order, but should I sent you the order as well?

**Comment by Shorashim** [comment]
What does it need to be sized at? I just really messed this up by uploading the image as is

**Comment by Shorashim** [comment]
How do I delete one? I found the admin page, but worried I would delete the whole thing...

**Comment by IshaDakota** [comment]
You don't need to worry about size at all - it resizes automatically. It looks like it is creating a double width frame though - we'll fix that.... just keep uploading.

**Comment by IshaDakota** [comment]
under content --> don't touch anything under edit view.

**Comment by Shorashim** [comment]
okay i will keep uploading and then we can go over the order and make sure its all centered and not weirdly aligned like it is now?

Also, should scroll automatically
