### ISSUE TITLE
TAGLIT

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#31]
Instagram needs to be edited from #Taglit to #Birthright

**Comment by IshaDakota** [comment]
Please have the degner send a new image

**Comment by Shorashim** [comment]
I can just edit it in photoshop and resend the homepage. Does that work?

**Comment by IshaDakota** [comment]
sure

**Comment by Shorashim** [comment]
How is best to send it to you? It won't let me send the file or zipfile. Also, if you go into the PSD homepage design under instagram feed, you can type it in, if that's easier by any chance. Let me know

**Comment by IshaDakota** [comment]
Put it in the dropbox if you can. If not, I can edit.

**Comment by Shorashim** [comment]
Added to dropbox

**Comment by IshaDakota** [comment]
muchos gracias
