### ISSUE TITLE
Taglit above layout bar

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#33]
How do I remove this?

**Comment by IshaDakota** [comment]
I don't understand the question

**Comment by Shorashim** [comment]
Sorry meant to write logo. It says Taglit-Birthright Israel, not Birthright Israel. How do I edit this?

**Comment by IshaDakota** [comment]
Do you mean the main logo in the header? 
![share_the_gift___shorashim](https://cloud.githubusercontent.com/assets/688507/9156668/bf93de42-3ea7-11e5-891e-5bab17fed39c.png)

**Comment by IshaDakota** [comment]
Still don;t understand if you want to change the logo or if there is some text that you want to change. If there is a new Taglit logo, please send to me.

**Comment by IshaDakota** [comment]
fixed in master
