### ISSUE TITLE
Trip Options

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#34]
Few issues:
1.Not up to date-when will this be up-to-date with version in PSD to be able to edit?
2. Birthright Plus button will need to be removed once up to date
3. Do I place in anchors for each section or are you both doing that?

**Comment by Shorashim** [comment]
Additionally, were the community trips the only image sliders provided? I have a feeling we have the same problem here that we had with the itineraries. Please advise if I should be reaching out to our designer

**Comment by IshaDakota** [comment]
I am assuming this is referring to the page, not the homepage eleent

>1.Not up to date-when will this be up-to-date with version in PSD to be able to edit?

You need to add all of the trip options  --under Add content --> Trip Option

>2. Birthright Plus button will need to be removed once up to date
Just remove the content.

>3. Do I place in anchors for each section or are you both doing that?
We will... note we can only anchor to the 4 main trip types (National College Campus NIche) - we cannot make a tab open from am anchor -- technically not possible.

>Additionally, were the community trips the only image sliders provided? I have a feeling we have the >same problem here that we had with the itineraries. Please advise if I should be reaching out to our >designer

Don't understand this question

**Comment by Shorashim** [comment]
1. Referring to actual page, but also the homepage does need to get edited
2. Didn't realize that-will add the individual content
3. What do we do about special needs trips then? The designers had told us this was possible.
4. Do you remember how they hadn't originally sent all the photos for the itineraries and I had to ask them to reformat everything for us? I have a feeling we have the same issue with this, as there should be formatted photos in each section. Am I missing something or are they not there? Call me if it's easier to go over this part over the phone.

**Comment by IshaDakota** [comment]
> What do we do about special needs trips then? The designers had told us this was possible.
It's not - those are opened by javascript, and you need to be on the page for the script to fire. for the specialty trips, we can anchor to the niche section.

**Comment by Shorashim** [comment]
Do you mean for special needs trips?

**Comment by Shorashim** [comment]
Also, are the images there for each section? There should be a collage for each section like with sample itinerary? If not, will reach out to Socialink, the design company

**Comment by IshaDakota** [comment]
I don't see any.

**Comment by Shorashim** [comment]
I'm very confused about these photo collages. I apologize, as I said I have never done anything like this before. Are you able to call me when you have five minutes? I think this may be easier to clarify over the phone rather than go back and forth

**Comment by Shorashim** [comment]
For the AEPi section, I realize they didn't format correctly in the PSD version, unless I am missing something. Is there a way to format this nicely with the quotes?

**Comment by Shorashim** [comment]
Also, can we fix the spacing between the options on Experience Israel With Israel With Your Campus? Very cluttered.

**Comment by IshaDakota** [comment]
fixed
