### ISSUE TITLE
Header Images

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#35]
Alumni-Does not work at smaller widths
Staffing-Does not work at smaller widths
Trip Options-Does not work at smaller widths
How To Register-Does not work at smaller widths
Start/Update Application-Does not work at smaller widths
FAQS-Does not work at smaller widths

**Comment by IshaDakota** [comment]
I reviewed all of these and if we want to use these particular images, they will need to redesign these to add more height at least 400 px (some of them are less then 300)

**Comment by IshaDakota** [comment]
Share the gift height needs fixing, all else is done.
