### ISSUE TITLE
Staff Application

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#37]
https://docs.google.com/forms/d/13xhDp5CpEeVKIJgNr8JzMSEVeU_nok0u7213d9tKINo/viewform

Is there a way to embed this or do we have to use a different form on the site?

**Comment by IshaDakota** [comment]
we can definitely embed.

It will look a bit different than designed because google doesn't give you much control over the style - but if that's OK, it will work.

**Comment by Shorashim** [comment]
Sounds good! I just checked in with Rachel to make sure this is what she wanted, but I think it makes sense. Alternatively, we can have an abbreviate application for this portion of the website or link directly to the Google Form. Any insight or suggestions?

**Comment by IshaDakota** [comment]
LET'S TRY TO EMBED - IF IT DOESN'T LOOK GOOD, WE WILL LINK.

sorry for shouting... forgot to take off caps lock ;)

**Comment by IshaDakota** [comment]
Can you share that google form with me, or paste the embed code here?

**Comment by Shorashim** [comment]
Reached out to Rachel. Need to her to share with us. Waiting on response.

**Comment by IshaDakota** [comment]
Labeling "needs design - but really waiting for Rachel.

**Comment by Shorashim** [comment]
Rachel shared the design. Let us know if this works. If it is too long, can we just embed the beginning? If it looks bad, we can link out.

**Comment by IshaDakota** [comment]
@Shorashim Please change these embeds to links

**Comment by Shorashim** [comment]
Done
