### ISSUE TITLE
Editing Pages

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#39]
Tried to edit eligibility by pasting the content from our old website and this happened:
http://dev-israel-with-israelis.pantheon.io/faq/eligibility

Can we undo? How do I do this in the most efficient way?

**Comment by IshaDakota** [comment]
1 of 2 things

Use the "paste as text" feature and then style the text or paste as is and change the styles.

![edit_page_element_important_travel_informtion___shorashim](https://cloud.githubusercontent.com/assets/688507/9156751/a060840a-3eaa-11e5-82f2-f4d5018fc813.png)

**Comment by Shorashim** [comment]
How do I make sure it only edits for one of the sections though? It just went over all the general FAQ verbiage

**Comment by IshaDakota** [comment]
???

**Comment by IshaDakota** [comment]
Oh, I see the problem... hold off for about 20 mins.

**Comment by IshaDakota** [comment]
These are ready to edit
