### ISSUE TITLE
Sliders

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#43]
When these are revised, will they be able to stretch across the full screen on a large desktop? I was under the impression that our goal was that the design would stretch the entire screen on a large desktop but collapse to function for smaller browser screens/tablets/mobile?

**Comment by IshaDakota** [comment]
i limited the width to a fairly wide desktop (i Think 1800px). If you want full edge to edge on the largest screens you need MUCH bigger and wider pictures. They also need to look good at varying widths. Finding images like this are an art... a needle in a haystack.

Further... images with people, don't often work well in these cases because you will inevitably lose focus. 

If you want full edge to edge, I recommend that you have them professional shot and cropped.

**Comment by IshaDakota** [comment]
The final (but perhaps temporary) solution was to slice the sliders from the PSD and include all of the text overlays. This means that the text is no longer editable, but it's the best solution unti we find images that are much more suitable.

Closing for now.

**Comment by Shorashim** [comment]
Sending ours in comparison to other TOs on the large screen. Can't go live with this like this. I thought the changes were meant to correct this issue?
![screen shot 2015-08-10 at 6 23 31 am](https://cloud.githubusercontent.com/assets/13404688/9170464/ba03b552-3f28-11e5-950c-7411c52298d9.png)
![screen shot 2015-08-10 at 6 23 54 am](https://cloud.githubusercontent.com/assets/13404688/9170468/ca6178a8-3f28-11e5-8bb9-e3e15745b0d0.png)
![screen shot 2015-08-10 at 6 24 39 am](https://cloud.githubusercontent.com/assets/13404688/9170470/cc17f94c-3f28-11e5-89dd-10d8eeb7bbf6.png)

**Comment by IshaDakota** [comment]
you need new images then.

![birthright_israel__israel_experiencebirthright_israel__israel_experience](https://cloud.githubusercontent.com/assets/688507/9170630/1e7e6de6-3f2a-11e5-9cdf-8dca8f2d0d15.png)

This is 2500 px and does not height adjust at all:
![birthright_israel__israel_experiencebirthright_israel__israel_experience](https://cloud.githubusercontent.com/assets/688507/9170644/3b69bfb4-3f2a-11e5-8703-f72166743069.png)

How do you want to handle?

**Comment by Shorashim** [comment]
The Hillel page seems to adjust well to different browser sizing settings. Is there anyway to set up our images like that? This is a focal point of the website and these pictures were carefully chosen based on guidance from the design team of what would work.

**Comment by IshaDakota** [comment]
Those images are 2800 pixels wide. Ours are 1600. We can stretch them, but
they would be pixelated, and the height would fill the entire screen.

**Comment by Shorashim** [comment]
1. Would an image like this work?
![screen shot 2015-08-10 at 7 04 38 am](https://cloud.githubusercontent.com/assets/13404688/9171056/19a4cc76-3f2e-11e5-89a8-7f7bb3f30e0b.png)

2. For the smaller images, could we slice them like Israel Experience did and then have it fit, but also work on different screen sizes?

**Comment by IshaDakota** [comment]
Lauren, please close this if we are done with sliders... thanks.
