### ISSUE TITLE
Countdown Bar Versions

### ISSUE THREAD

**Issue by IshaDakota** [MarchingLizard/iwiorg#46]
*Version One: Registration not yet open*
Pre-register
Should have countdown like it does now
Verbiage
Help secure your spot for a future trip
Pre-register for winter and summer trips

*Version Two: Registration Open*
Countdown is replaced with apply now button
Verbiage:
What are you waiting for?
Apply now for December, January, and February Trips
You can still pre-register for Summer 2016 trips here
Question: Does that make sense?

*Version Three: Registration closing soon*
Time is running out...don't miss your chance
Apply now for December, January, and February TripsYou can still pre-register for Summer 2016 trips here

*Version Four: Registration is now closed*
Clock changes to pre-register now button
Verbiage:
Winter 2015/2016registration is now closed.  
Help secure your spot for summer 2016 and winter 2016/17 by pre-registering now.

**Comment by Shorashim** [comment]
Pre-registration bar still needs to be centered and text needs to be updated:
![screen shot 2015-08-10 at 8 42 00 am](https://cloud.githubusercontent.com/assets/13404688/9176443/f81c2b62-3f50-11e5-97a8-43e7aea29cdb.png)

**Comment by IshaDakota** [comment]
fixed
