### ISSUE TITLE
Niche trip-New photo needed

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#49]
Emailing Israel office about getting a new image to replace the niche trip surfing picture, as we are not doing Birthright plus. Anything I should now while searching for this image?

**Comment by IshaDakota** [comment]
It's highly landscape, but actually we can use height as well, so not really... try to get something mostly landscape, as it will look better.

**Comment by Shorashim** [comment]
I assume this wouldn't work?

![resized lgbt flag kotel](https://cloud.githubusercontent.com/assets/13404688/9175178/d4ee28d6-3f49-11e5-832b-c84fb2eff1d2.jpg)

Waiting to hear back from Israel office.

**Comment by IshaDakota** [comment]
we could crop the bottom third of it.

**Comment by Shorashim** [comment]
Let's see how that looks. Should work for now!

**Comment by IshaDakota** [comment]
eek, i don't think this will work.

![niche-banner](https://cloud.githubusercontent.com/assets/688507/9190342/9dde6e08-3fb9-11e5-8687-c8c3124cd239.jpg)

**Comment by IshaDakota** [comment]
![lgbtq](https://cloud.githubusercontent.com/assets/688507/9197374/435b8462-3ff9-11e5-96d3-185c2f93ece8.jpg)

Not sure about this either, it's a really wide landscape frame.

**Comment by Shorashim** [comment]
Is there a way to adjust the first one so that the flag is centered?

**Comment by Shorashim** [comment]
Lauren Schmidt
Marketing & Communications Manager
Shorashim
Main line: 312-267-0677
Direct line: 312-380-6537
Fax: 312-276-4739
www.israelwithisraelis.com

**Comment by IshaDakota** [comment]
I used the full length of the image... I can crop but we will lose height.

**Comment by Shorashim** [comment]
I meant centered vertically (so it is just a flag centered against the Kotel). Alternatively, do you have any other suggestions? I am not sure if we have another image that works, but if you have any other suggestions, I can do my best to find something,

**Comment by Shorashim** [comment]
https://www.facebook.com/media/set/?set=a.10153342274289871.1073741893.20232329870&type=3

Will one of these work?
