### ISSUE TITLE
Alum of the Month

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#51]
Can we embed it or will it look bad?

**Comment by IshaDakota** [comment]
I don't know what this is. google form? on the design it's just a link (with no URL).

**Comment by IshaDakota** [comment]
I see now... I embedded it.... what do you think?

**Comment by Shorashim** [comment]
I don't think I like it. Do you like it? It doesn't go with the brand, so I think it's best to just link it out. Agreed?

**Comment by IshaDakota** [comment]
Yeah... check it out on the staff application page as well... don't love it. I think we should just do links to the forms in these cases. Agreed.  If so just comment and close.

**Comment by Shorashim** [comment]
Not as bad, but I don't love it either. Let's just link.
