### ISSUE TITLE
Application checklist

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#53]
How do I upload with the checkmark graphics? Is this something you can do?

**Comment by IshaDakota** [comment]
yes. In every case where there is an image that you can't insert, leave it out and leave me a note or an issue like this.

**Comment by Shorashim** [comment]
I'm not sure still how to export the image. Is it easy/something you could explain to me how to do?

If not, could I paste the text and screenshot here for you to upload? Will do whatever is easiest for both of us.

**Comment by IshaDakota** [comment]
Just leave a note... if it's on the PSD I can grab it.

**Comment by Shorashim** [comment]
I did in the launch document. Thanks!
