### ISSUE TITLE
H3 Font is inconsistent on Staffing page

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#56]
Not consistent. Can we please fix this?

**Comment by IshaDakota** [comment]
different from what?

**Comment by IshaDakota** [comment]
never mind, I see. Try to be as specific as possible, like: "The H3 font on this page is different than on other pages"

This could have meant page header, header image, or the whole site header.... screen shots can help where words fail.

**Comment by Shorashim** [comment]
Will do. Sorry about that.
