### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by IshaDakota** [MarchingLizard/iwiorg#6]
Current dev version:
![home___site-install_and_homepage_psd___100___your_application__rgb_8___](https://cloud.githubusercontent.com/assets/688507/8765935/578cd7fe-2dea-11e5-92c8-060626572115.png)

**Comment by Shorashim** [comment]
Adding "The Gift" section on the first column on the left

**Comment by IshaDakota** [comment]
@Shorashim Where does the subscribe lik at the top of the footer go?

<img width="985" alt="banners_and_alerts_and_home___site-install" src="https://cloud.githubusercontent.com/assets/688507/8767263/8fb9fef4-2e1c-11e5-91de-ab67b2824f5e.png">

**Comment by Shorashim** [comment]
It should link to the email list, so either a pop-up or that portion of the page. Whatever is most user friendly. Of course, when Birthright removes the sign up lists from all TOs, this will need to change, but I want to utilize it in the meantime. What do you think?
