### ISSUE TITLE
Blog Headers

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#60]
Does this work? I can create something different, but figured it could look good!

![into the woods](https://cloud.githubusercontent.com/assets/13404688/9186298/00ff5f1e-3f89-11e5-9428-5c16a55fdff8.png)

**Comment by IshaDakota** [comment]
Doesn't really work - less landscape and bigger overall.

**Comment by Shorashim** [comment]
Are you able to send me suggested pixels and I can create something? Or is this any better?
![l i g h t h o u s e](https://cloud.githubusercontent.com/assets/13404688/9190047/5c69f6a2-3fb6-11e5-8366-a316f3d47c6b.png)

**Comment by Shorashim** [comment]
If this size works, I can edit it and make it look better

**Comment by IshaDakota** [comment]
i thionk this will work... more than 800x400 is best

**Comment by Shorashim** [comment]
Okay let's try and I can always create something tomorrow and add it in myself, right?
