### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#61]
How do we control what shows up for this?
![unnamed-3](https://cloud.githubusercontent.com/assets/13404688/9189518/237e43ae-3faf-11e5-8ee3-caf5577865ab.png)
![unnamed-2](https://cloud.githubusercontent.com/assets/13404688/9189519/268cedd4-3faf-11e5-9ac7-a00f67bb04a2.png)
![unnamed-1](https://cloud.githubusercontent.com/assets/13404688/9189521/28cf29fe-3faf-11e5-8a50-b799b5456c85.png)
![screen shot 2015-08-05 at 8 14 29 pm](https://cloud.githubusercontent.com/assets/13404688/9189523/2d836550-3faf-11e5-9f4c-0d60d283d8a6.png)
![screen shot 2015-08-05 at 8 12 39 pm](https://cloud.githubusercontent.com/assets/13404688/9189524/30368138-3faf-11e5-8b52-5fd3033cb48f.png)
![screen shot 2015-08-05 at 8 12 27 pm](https://cloud.githubusercontent.com/assets/13404688/9189526/340c2290-3faf-11e5-8738-50d6be9eca24.png)

**Comment by IshaDakota** [comment]
Only google controls... through webmaster tools, you can exclude links from being made.

**Comment by Shorashim** [comment]
There is no way to control the verbiage that shows up? How were some TOs able to add Pre-registration then? Ours still said Taglit and I don't want it to say that. Isn't there a way to code this with tags to control what the summaries are? Thanks for your help!

**Comment by IshaDakota** [comment]
As far as I know there is now way to control this except to block certain things you do not want as site links. If there is any more to learn here, you would need an SEO consultant.
