### ISSUE TITLE
Side pop out

### ISSUE THREAD

**Issue by IshaDakota** [MarchingLizard/iwiorg#63]
![home___site-install](https://cloud.githubusercontent.com/assets/688507/9197744/ab4bc80e-3ffc-11e5-890d-9aa88d3b8bfe.png)

Is there supposed to be a different button for pre-registration?

**Comment by Shorashim** [comment]
It should just say pre-register now. Can that just be edited within photoshop?

**Comment by IshaDakota** [comment]
done
