### ISSUE TITLE
Pay It Forward

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#64]
Can there be a dropdown to Pay It Forward on the "Share The Gift" menu?

![screen shot 2015-08-11 at 7 49 50 am](https://cloud.githubusercontent.com/assets/13404688/9197865/95b23b94-3ffd-11e5-8cdd-7f10661cca35.png)

**Comment by IshaDakota** [comment]
If there is a dropdown then the top level becomes a non-linkable header. you would then need something like:

The Gift
- share the gift
- pay it forward

**Comment by Shorashim** [comment]
Got it. Let's leave it off for now. We will link directly to Pay It Forward in the homepage slider and sidebar, so it should suffice
