### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#66]
The resolution, alignment, and footer still looks very weird on mobile

**Comment by IshaDakota** [comment]
please be (much) more specific.

**Comment by Shorashim** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/13404688/9198921/0a42e1aa-4005-11e5-929e-3448c7147bf9.png)
![unnamed-1](https://cloud.githubusercontent.com/assets/13404688/9198928/19e8d326-4005-11e5-8a4f-78c7220feddc.png)
![unnamed-2](https://cloud.githubusercontent.com/assets/13404688/9198932/20c1cb26-4005-11e5-94ba-dbf1a780f737.png)

**Comment by IshaDakota** [comment]
1. Footer heights and wrapping fixed

2. The images for those trip options are pretty sloppily put together (making it appear to have margins) - we should ask for new images, but I don't think this is critical enough to hold anything up.

3. that countdown timer uses javascript which is somewhat unpredictable across all the browsers (particularly the many android browsers). Our only option for complete uniformity is to hide it on the narrowest widths.

See for instance my phone (iPhone)
![2015-08-11 09 39 13](https://cloud.githubusercontent.com/assets/688507/9200476/9987837c-400d-11e5-8a87-205506e28236.png)

**Comment by Shorashim** [comment]
1. Great!
2. I am going to email them now. Is there something particular I should say or can I just loop you in? I will have everyone review with it like that, but would love for it to be fixed before going live. You are correct - it looks sloppy!
3. Let's remove the timer on the narrowest widths then

**Comment by IshaDakota** [comment]
I think I can handle this without sending to the designer.

**Comment by IshaDakota** [comment]
Check it out now... I think its much better.

**Comment by Shorashim** [comment]
Much better!!
