### ISSUE TITLE
Shortening Homepage

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#68]
Can we remove some of the white space at the top and bottom of the logo bar? I remember this was an issue in the design process. I know the things that I am sending seem very small and particular, but I just want it to be perfect and as close to what we anticipated as possible. Thanks again!

![screen shot 2015-08-11 at 2 10 01 pm](https://cloud.githubusercontent.com/assets/13404688/9207376/e2d61c08-4032-11e5-9869-f9c0da7190e2.png)

**Comment by IshaDakota** [comment]
<img width="1425" alt="home___birthright_israel__shorashim" src="https://cloud.githubusercontent.com/assets/688507/9977404/46fb3364-5ecc-11e5-902d-73372ea07704.png">

**Comment by Shorashim** [comment]
Looks good!
