### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by IshaDakota** [MarchingLizard/iwiorg#7]
This is the design:
https://www.dropbox.com/s/qi6tlhqq66pdbpm/About.psd?dl=0

**Comment by IshaDakota** [comment]
@Shorashim I'm still confused about the sidebar navigation menu. In the sitemap you provided, the About page does not appear. What is the sidebar menu supposed to look like when on a page that is not included in the menu?

**Comment by Shorashim** [comment]
The about page is in the small menu bar:
-Testimonials
-About Taglit Birthright Israel
-Why Shorashim

Does that make sense for the sidebar?

**Comment by IshaDakota** [comment]
putting merged screenshot here for possible
![about_us___site-install_and_your_application_psd___66_7___rectangle_12__rgb_8____and_style_scss](https://cloud.githubusercontent.com/assets/688507/8884591/8ea16e12-321d-11e5-98a6-85bc590d93a1.png)
 further comment:

**Comment by Shorashim** [comment]
Spacing is still a little off. Looks kind of scrunched. Anything we can do to fix it?

**Comment by Shorashim** [comment]
Flagging again for testimonials extending too far down in smaller browsers

**Comment by IshaDakota** [comment]
merged
