### ISSUE TITLE
External Resources on dropbox

### ISSUE THREAD

**Issue by IshaDakota** [MarchingLizard/iwiorg#71]
For the moment, and maybe permanently, let's host external resources (like itineraries) on a public dropbox folder and link to them there. This way we will have consistency when we switch over.

For now we are talking about 

* Aspergers itinerary
* packing list

**Comment by Shorashim** [comment]
@IshaDakota uploaded here: https://www.dropbox.com/sh/cxh5ywikhpaiauz/AAC8YX3PpFXA1DT3Ma818B1Ia?dl=0

**Comment by IshaDakota** [comment]
These need to each be sharable links in order to be linked in.

**Comment by Shorashim** [comment]
Zach always does this, so I don't want to mess anything up. How do I do this?

**Comment by IshaDakota** [comment]
got it.
