### ISSUE TITLE
Create Blog Posts

### ISSUE THREAD

**Issue by IshaDakota** [MarchingLizard/iwiorg#73]
@Shorashim 
Can you create the two additional blog posts?

Two steps:
1. Content --> Create Bus (Title is the Generic name like "Chicago Community, blah) Bus Code is the "SH" code
2,Content --> Create Blog Post (add the post and choose the appropriate bus)

**Comment by Shorashim** [comment]
Got it! Should I wait until the image sizing is revised? I can upload these first thing in the morning

**Comment by IshaDakota** [comment]
we can resize images afterwards

**Comment by Shorashim** [comment]
Can you please grant me access to upload images?

**Comment by IshaDakota** [comment]
weird... cant find the permission setting... just giving you full admin access... be careful ;)

**Comment by Shorashim** [comment]
I'll try my best. Hoping on a call and then I will add images.

**Comment by Shorashim** [comment]
I will try my best!

**Comment by Shorashim** [comment]
Still won't let me add :(

**Comment by IshaDakota** [comment]
Did you change the text filter to "Full HTML"?  (dropdown below the body field.

**Comment by Shorashim** [comment]
![screen shot 2015-08-12 at 10 51 28 am](https://cloud.githubusercontent.com/assets/13404688/9228889/2f9b537a-40e0-11e5-9b2a-68a0c304961e.png)

**Comment by IshaDakota** [comment]
you should be able to upload images into the body now.
