### ISSUE TITLE
Tagging Blogposts

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#75]
Eventually, will we be able to tag the posts with keywords such as Masada, Jerusalem, Israel With Israelis, etc?

**Comment by Shorashim** [comment]
Low priority can't figure out how to flag it

**Comment by IshaDakota** [comment]
will add tagging feature after launch - no problem

**Comment by Shorashim** [comment]
Perfect. Thank you! :+1:
