### ISSUE TITLE
Spacing on Blog

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#76]
Can we expand the spacing between posts? Quite scrunched.
![screen shot 2015-08-12 at 7 43 08 am](https://cloud.githubusercontent.com/assets/13404688/9224143/d370441c-40c5-11e5-95b8-c2ae36e1dcbe.png)

**Comment by Shorashim** [comment]
Additionally, how do I control the text that shows up in the preview portion (ie where it says "Jeremy Kazzaz Where are you from originally?" On the old site, it worked when I changed the summary, but right now, that is not working.

**Comment by IshaDakota** [comment]
two options:

1. (the way it is now): it grabs the first 300 charachters of text.

2. Create a summary field like the old site

Your pref... the latter is harder to maintain as a content editor, but if you're willing more customizable.

easy to do both ways.

**Comment by Shorashim** [comment]
Let's do #2. Sometime I don't want the first 300 characters because sometimes it's not good. Thanks!

**Comment by IshaDakota** [comment]
both issues fixed.

**Comment by Shorashim** [comment]
Summary issue is not rectified yet.

**Comment by IshaDakota** [comment]
It is. Always try refreshing if you don't see a change. Also, sometimes the cache needs to be cleared which happens every half hour or so.

**Comment by Shorashim** [comment]
Ah okay sorry I will try again!
