### ISSUE TITLE
Logo Change

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#77]
Michal is saying we have the wrong Shorashim logo. I think she is right. Should be this:

https://www.dropbox.com/sh/39s7n9jus06xut7/AADoJ5C2Z0v936VKrouD1J5ma?dl=0

Sent to you via email as well

**Comment by Shorashim** [comment]
Resent via email

**Comment by IshaDakota** [comment]
cool.  I'm sure there's a difference... not seeing it though.... what is it?

**Comment by Shorashim** [comment]
It's really small, but the bubbles are closer in size and this is the second version of our redesign.

**Comment by IshaDakota** [comment]
excellent.  it looks like the same dimensions, so it should be easy to swap it out. Good catch.

**Comment by Shorashim** [comment]
Perfect. Let me know if it works. It should be different :)

**Comment by IshaDakota** [comment]
changed - it has different dimensions than the old logo, so it looks a little different.
