### ISSUE TITLE
Itinerary Update

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#79]
Michal wants these updated, so I will have new text which is not a problem and new map images. Anything I should know before redoing this?

**Comment by Shorashim** [comment]
Realizing headers may need to change pending the new version Zach puts together

**Comment by IshaDakota** [comment]
Has this been done? At the moment headers look fine.

**Comment by Shorashim** [comment]
Almost done. Zach and I are going over the text first thing today and then changing the maps. Will update this once complete

**Comment by Shorashim** [comment]
Are you able to upload the itinerary collages in PSD? There are a few adjustments that I need to make and I cannot edit the PNGs. Thanks!

**Comment by IshaDakota** [comment]
They are on the original PSD for the page. If you need them isolated, you'll need to get them from the designer.
