### ISSUE TITLE
Edit Mailchimp Signup Form

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#81]
Birthright Logo Needs To Be Added

![screen shot 2015-08-12 at 10 57 01 am](https://cloud.githubusercontent.com/assets/13404688/9229055/e5272e6c-40e0-11e5-9a24-c42972a6f0a9.png)

**Comment by IshaDakota** [comment]
@Shorashim Can you please make all changes to the mail chimp templates? It is easily editable under the list --> signup forms -->General Forms

**Comment by Shorashim** [comment]
Updated
