### ISSUE TITLE
Register Now Button

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#82]
Is it possible for this to be a pre-register now button and switch once registration opens? This is on the how to register page

![screen shot 2015-08-13 at 10 07 18 am](https://cloud.githubusercontent.com/assets/13404688/9253437/69d4735a-41a3-11e5-9e75-05d39ad13fb9.png)

**Comment by IshaDakota** [comment]
Does this button exist or does it need to be made?

**Comment by Shorashim** [comment]
Needs to be made. Is it easier for me to make it or are you able to edit text?

**Comment by Shorashim** [comment]
Does this work? I am not sure if I did this correctly.

https://www.dropbox.com/sh/06iiaioz89n3yly/AABygzXpkE-g6wdE07F7afSWa?dl=0

**Comment by IshaDakota** [comment]
This works fine - nice work... closing, but remind me to ask about placement on page with accordion text
