### ISSUE TITLE
Homepage Facebook Pixel Code

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#87]
Homepage: 
<script>(function() {
var _fbq = window._fbq || (window._fbq = []);
if (!_fbq.loaded) {
var fbds = document.createElement('script');
fbds.async = true;
fbds.src = '//connect.facebook.net/en_US/fbds.js';
var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(fbds, s);
_fbq.loaded = true;
}
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', '6017259126581', {'value':'0.00','currency':'USD'}]);
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=6017259126581&amp;cd[value]=0.00&amp;cd[currency]=USD&amp;noscript=1" /></noscript>

**Comment by IshaDakota** [comment]
closed in favor of #89
