### ISSUE TITLE
Testimonial quotes are too long

### ISSUE THREAD

**Issue by IshaDakota** [MarchingLizard/iwiorg#9]
@shorashim I think some of the testimonial quotes are too long and I'd like to make the font more readable here. Is it possible to make these shorter and more constant
<img width="1440" alt="about_us___site-install" src="https://cloud.githubusercontent.com/assets/688507/8841813/7fae174c-30c0-11e5-842f-7f4020ba03e9.png">
 in length?

**Comment by Shorashim** [comment]
Is it possible to extend it so it covers more space and has more line spacing between it?  I can try to find other quotes, but we were hoping it would be easy to switch testimonials in and out (some long and some short). Is that possible?

**Comment by IshaDakota** [comment]
It's possible, but it will look like it does in the design, with the quotes
much longer than the viideo beside it. I think it looks weird and that
nobody will read long quotes like that, but we can make it as it is
designed (although everything needs to be a little narrower as discussed.

**Comment by Shorashim** [comment]
I think it looks fine in the version you attached. Are we able to change the quotes when we want to? If so, I think that should be fine

**Comment by IshaDakota** [comment]
Yes quotes are editable and you can swap quotes in/out very easily,
