### ISSUE TITLE
Itineraries and Packing Lists

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#93]
Is there a way to not link this to dropbox? I really don't feel comfortable having it organized that way. Can we link it to a pdf like we have in the past?

**Comment by IshaDakota** [comment]
I agree - this doesn't look how I expected. We will find a better way.

**Comment by Shorashim** [comment]
How can we do it how we did in the past? It just linked a PDF as a page. I think that worked.
