### ISSUE TITLE
Bottom Menu Bar

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#96]
About section is still missing (left hand column, should be first one)

About
--About Us
--Alumni
--Blog
--Staffing

Does that make sense?

**Comment by IshaDakota** [comment]
<img width="1352" alt="share_the_gift___birthright_israel__shorashim" src="https://cloud.githubusercontent.com/assets/688507/9977288/f37e2818-5ec6-11e5-8578-1b7bf4c8eb0a.png">

**Comment by Shorashim** [comment]
Looks good! For "share the gift" is it possible to have it as follows:
Pay It Forward
Become an Ambassador
Campus Recruiting Program

Could we anchor to that header on each page? Just a thought!

**Comment by IshaDakota** [comment]
<img width="1432" alt="share_the_gift___birthright_israel__shorashim_and_style_scss" src="https://cloud.githubusercontent.com/assets/688507/9977306/7cf86162-5ec7-11e5-9dbc-73ec496a2d1d.png">

Also look at this... not sure at what stage the headers became all caps, but if you like it, it keeps all headers on one line.

**Comment by Shorashim** [comment]
I'm okay with that! Thanks!
