### ISSUE TITLE
Pre-Register Page

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#97]
Can we please create www.israelwithisraelis.com/preregister and link to this https://register.birthrightisrael.com/index.cfm?org=29&Name=PreRegisterPage? through http://bit.ly/1MtV4O7?

**Comment by IshaDakota** [comment]
Do you want a page with a link or do you want to link directly to the first link... and then why the bitly at all?

**Comment by Shorashim** [comment]
We should use the bit.ly to track clicks, so just link to http://bit.ly/1MtV4O7. Sound good?

**Comment by IshaDakota** [comment]
Got it.

**Comment by IshaDakota** [comment]
Done.

You can handle all redirects at: http://www.israelwithisraelis.com/admin/config/search/redirect

You should do these all as redirects rather than aliases.
