### ISSUE TITLE
Updating Trip Dates

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#99]
Where are we able to update this? It doesn't seem to be showing up in the content. This needs to be easily editable, as with the last website, it was a little hard to update things.

Additionally, we want to add summer trip dates soon with a similar format. I would want to put this below the winter table with text above it.

Can we also specifically link to trip dates from different seasons like how we specifically link to national trips and community trips in the trip options section?

**Comment by IshaDakota** [comment]
This is a simple table that is editable as a page element. You may not be seeing it because it is a separate element from the text at the top. We can add another table underneath it (actually you can copy an paste the current table if you want).

Closing  - re-open if I misunderstood..
